# SPDX-License-Identifier: Apache-2.0
"""Generate the docs site's Markdown and llms files from the packaged guides and live catalogs.

    uv run python tools/gen_docs.py          # write
    uv run python tools/gen_docs.py --check  # exit 1 if any generated file is stale

Sources of truth: ``src/signalquarry/guides/*.md``, the CLI command registry, the
reason-code registry and, for the generated block of ``docs/design/ARCHITECTURE.md``,
the source tree itself (``tools/gen_architecture.py``). Never edit the generated files by hand.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from signalquarry.api.docs import GUIDES, cli_markdown, guide, llms_full, llms_index, reason_codes_markdown
from signalquarry.cli.main import command_catalog

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_architecture  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
HEADER = "<!-- Generated by tools/gen_docs.py from {source}; do not edit. -->\n\n"


def generated() -> dict[Path, str]:
    catalog = command_catalog()
    files = {
        DOCS / f"{name}.md": HEADER.format(source=f"src/signalquarry/guides/{name}.md") + guide(name)
        for name, _ in GUIDES
    }
    files[DOCS / "reference" / "cli.md"] = HEADER.format(source="the CLI registry") + cli_markdown(catalog)
    files[DOCS / "reference" / "reason-codes.md"] = (
        HEADER.format(source="the reason-code registry") + reason_codes_markdown()
    )
    architecture = DOCS / "design" / "ARCHITECTURE.md"
    files[architecture] = gen_architecture.apply(architecture.read_text(encoding="utf-8"))
    files[DOCS / "llms.txt"] = llms_index(catalog)
    files[DOCS / "llms-full.txt"] = llms_full(catalog)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, text in generated().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print("stale generated docs (run tools/gen_docs.py):", *stale, sep="\n  ")
        return 1
    print("updated:" if stale else "up to date", *stale, sep="\n  " if stale else "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
